# Generated by Django 5.0.4 on 2024-04-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_remove_platform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Land', 'Land'), ('Industrial', 'Industrial'), ('Special Purpose', 'Special Purpose')], max_length=20),
        ),
    ]
