# Generated by Django 5.0.4 on 2024-04-23 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_alter_thread_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='platforms.platform'),
        ),
    ]
