# Generated by Django 5.0.4 on 2024-04-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='platforms.platform'),
        ),
    ]
