# Generated by Django 5.0.4 on 2024-04-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0010_alter_bid_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, default='houses.png', upload_to=''),
        ),
    ]
