# Generated by Django 5.0.3 on 2024-04-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0011_platform_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
