# Generated by Django 5.0.3 on 2024-04-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_alter_platform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='image',
            field=models.ImageField(blank=True, default='houses.png', upload_to=''),
        ),
    ]
