# Generated by Django 5.0.3 on 2024-04-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0016_platform_owner_contact_number_delete_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='owner',
        ),
    ]
