# Generated by Django 5.0.4 on 2025-05-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0023_platform_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='is_sold',
        ),
    ]
